[mgr]
prepend_keymap = [
	{ on = "<Enter>", run = "open",        desc = "Open (hx / glow / system)" },
	{ on = "e",       run = "open --hovered", desc = "Edit in Helix" },
	{ on = "y",       run = "copy --hovered path", desc = "Yank path" },
]
